services:
  flask-app:
    build: aroot
    restart: always
    ports:
      - '8000:8000'
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:8000/flask-health-check || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    command: gunicorn -w 3 -t 120 -b 0.0.0.0:8000 app:app --access-logfile - --log-level debug
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8
    shm_size: 1gb
    restart: always
    healthcheck:
      test: [ 'CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password="${MYSQL_ROOT_PASSWORD}" --silent' ]
      interval: 3s
      retries: 5
      start_period: 30s
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=b_root
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    expose:
      - 3306
      - 33060

volumes:
  db-data:

